type FileMetadata @model @auth(rules: [
  { allow: owner },
  { allow: public, operations: [read] }
]) {
  id: ID!
  name: String!
  size: Int!
  type: String!
  key: String!
  owner: String! @index(name: "byOwner", queryField: "listFileMetadataByOwner", sortKeyFields: ["uploadTimestamp"])
  sharingStatus: SharingStatus
  shareExpiration: AWSDateTime
  uploadTimestamp: AWSDateTime!
}

type ActivityLog @model @auth(rules: [
  { allow: owner }
]) {
  id: ID!
  userId: String! @index(name: "byUser", queryField: "listLogsByUser", sortKeyFields: ["timestamp"])
  actionType: String!
  timestamp: AWSDateTime!
  fileId: String
  fileName: String
  ip: String
}

enum SharingStatus {
  PRIVATE
  PUBLIC
}
